app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageView, AboutPageView
from .views import MemorialListView,MemorialDetailView, MemorialCreateView, MemorialUpdateView, MemorialDeleteView
from .views import AddPhotoView, PhotoUpdateView, PhotoDeleteView
from .views import MessageCreateView, MessageUpdateView, MessageDeleteView


urlpatterns =[

    path('', HomePageView.as_view(), name ='home'),

    path('about/', AboutPageView.as_view(), name ='about'),

    # Memorial
    path('Memorial/', MemorialListView.as_view(), name ='Memorial'),
    path('Memorial/create', MemorialCreateView.as_view(), name ='Memorialcreate'),
    path('Memorial/<int:pk>/edit/', MemorialUpdateView.as_view(), name='Memorialupdate'),
    path('Memorial/<int:pk>/', MemorialDetailView.as_view(), name ='Memorialdetail'),
    path('Memorial/<int:pk>/delete', MemorialDeleteView.as_view(), name='Memorialdelete'),

    # Photo
    path('Memorial/<int:pk>/Photos/', AddPhotoView.as_view(), name='addphoto'),
    path('Memorial/<int:memorial_pk>/Photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='Photoupdate'),
    path('Memorial/<int:memorial_pk>/Photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='Photodelete'),

    #Message
    path('Memorial/<int:pk>/Message', MessageCreateView.as_view(), name='Messagecreate'),
    path('Memorial/<int:memorial_pk>/Message/<int:pk>/update', MessageUpdateView.as_view(), name='Messageupdate'),
    path('Memorial/<int:memorial_pk>/Message/<int:pk>/delete', MessageDeleteView.as_view(), name='Messagedelete'),



     ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jovero/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

app/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.template.context_processors import static
from django.template.context_processors import media
from django.conf import settings
from django.views.generic.dates import timezone_today



class Tag(models.Model):
    # memorial = models.ForeignKey('Memorial', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
   # memorials = models.ManyToManyField('Memorial', related_name='tagged_by')

    def __str__(self):
        return f"{self.name}"

class Memorial(models.Model):
    memorialid = models.AutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    dateofbirth = models.DateField()
    dateofdeath = models.DateField()
    biography = models.TextField()
    tags =models.ManyToManyField('Tag', related_name='memorial_tags')
    image = models.ImageField(null=True, blank=True, upload_to='images/')


    def __str__(self):
        return f"{self.firstname} {self.lastname}"

    def get_absolute_url(self):
        return reverse("Memorialdetail", kwargs={"pk": self.pk})




class Photo(models.Model):
    photoid = models.AutoField(primary_key=True)

    image = models.ImageField(null=True, blank=True, upload_to='photos/')
    datepost = models.DateTimeField(default=timezone.now)
    memorial = models.ForeignKey('Memorial', on_delete=models.CASCADE, related_name='photos')

    def __str__(self):
        return str(self.image)


class Message(models.Model):
    messageid = models.AutoField(primary_key=True)
    memorial = models.ForeignKey(Memorial, related_name='messages',on_delete= models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null = True)
    content = models.TextField()
    dateposted = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return '%s  %s - %s' % (self.memorial.firstname, self.memorial.lastname, self.user)

app/templates/app/Memorial/memorialcreate.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
    <title>New Post</title>

    <form action="{% url 'Memorialcreate' %}" method="post" enctype="multipart/form-data" class="formm">
        {% csrf_token %}

        <h1>NEW MEMORIAL</h1>

        <div>
            <label for="id_user">Created By:</label>
            <select id="id_user" name="user">
                {% for user in users %}
                    <option value="{{ user.pk }}" {% if user.pk == form.user.value %} selected {% endif %}>
                        {{ user }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="id_firstname">Firstname</label>
            <input type="text" id="id_firstname" name="firstname" value="{{ form.firstname.value }}">
            {% if form.firstname.errors %}
                <div class="error">{{ form.firstname.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="id_lastname">Lastname</label>
            <input type="text" id="id_lastname" name="lastname" value="{{ form.lastname.value }}">
            {% if form.lastname.errors %}
                <div class="error">{{ form.lastname.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="id_dateofbirth">Date of Birth</label>
            <input type="date" id="id_dateofbirth" name="dateofbirth" value="{{ form.dateofbirth.value }}">
            {% if form.dateofbirth.errors %}
                <div class="error">{{ form.dateofbirth.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="id_dateofdeath">Date of Death</label>
            <input type="date" id="id_dateofdeath" name="dateofdeath" value="{{ form.dateofdeath.value }}">
            {% if form.dateofdeath.errors %}
                <div class="error">{{ form.dateofdeath.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="id_biography">Biography</label>
            <textarea id="id_biography" name="biography">{{ form.biography.value }}</textarea>
            {% if form.biography.errors %}
                <div class="error">{{ form.biography.errors }}</div>
            {% endif %}
        </div>

        <div>
            <label for="id_tags">Tags</label>
            <select id="id_tags" name="tags" multiple>
                {% for tag in tags %}
                    <option value="{{ tag.pk }}" {% if tag.pk in form.tags.value %} selected {% endif %}>
                        {{ tag }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="id_image">Image</label>
            <input type="file" id="id_image" name="image" accept="image/*">
            {% if form.image.errors %}
                <div class="error">{{ form.image.errors }}</div>
            {% endif %}
        </div>

        <input type="submit" value="Save" class="input_button">
    </form>
{% endblock content %}

app/templates/app/Memorial/memorialdelete.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
      <h1> New Post</h1>
        <form action="{% url 'Memorialdelete' object.pk %}" method="post" class="formm" >
            {% csrf_token %}
            {{form.as_p}}
            <p>Are you sure you want to delete? {{memorial.firstname }}{{memorial.lastname}}</p>
            <input type = "submit" value="Confirm">


        </form>
{% endblock content %}

app/templates/app/Memorial/memorialdetail.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/memorial.css' %}">


<div class="product-card">
    <h2>{{ memorial.firstname }} {{ memorial.lastname }}</h2>
    <p>{{ memorial.biography }}</p>
    {% if memorial.image %}
        <img src="{{ memorial.image.url }}" >
    {% else %}
        <p>No image</p>
    {% endif %}
</div>


<a href="{% url 'Memorialupdate' memorial.pk %}" class="add_button">Edit</a>
<a href="{% url 'Memorialdelete' memorial.pk %}" class="add_button">Delete Memorial</a>

<h3 class="add_button">Photos</h3>

<div class="photo-gallery">

    {% for photo in memorial.photos.all %}
        <div class="product-card">
            {% if photo.image %}
            <h2>{{user.username}}</h2>
                <img src="{{ photo.image.url }}">
                <a href="{% url 'Photoupdate' memorial.pk photo.pk %}" class="anchor">Edit Photo</a>
                <a href="{% url 'Photodelete' memorial.pk photo.pk %}" class="anchor">Delete Photo</a>
            {% else %}

            {% endif %}
        </div>
    {% endfor %}
</div>

<a href="{% url 'addphoto' memorial.pk %}" class="add_button">Add Photo</a>



 <form method="POST" action="{% url 'Messagecreate' memorial.pk %}">
            {% csrf_token %}
            <textarea name="content" placeholder="WRITE A MESSAGE..." required></textarea>
            <input type="submit" value="Submit">
        </form>

 <hr>

        {% if not memorial.messages.all %}
            <p>No Message </p>
        {% endif %}
        {% for message in memorial.messages.all %}
        <div class="message">
            <p><strong>{{ message.user }}</strong> - {{ message.dateposted }}</p>
            <p>{{ message.content }}</p>

            <a href="{% url 'Messageupdate' memorial.pk message.pk %}" class="btn">Edit Message</a>
            <a href="{% url 'Messagedelete' memorial.pk message.pk %}" class="btn">Delete Message</a>
        </div>
    {% empty %}
        <p>No messages available.</p>
    {% endfor %}


{% endblock content %}

app/templates/app/Memorial/memoriallist.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

<a href="{% url 'Memorialcreate' %}" class="add_button">+ New Memorial</a>

<link rel="stylesheet" href="{% static 'css/memorial.css' %}">


 <div class="card-container">
<form method="get" action="{% url 'Memorial' %}">
    <label>
        <input type="text" name="q" placeholder="Search....." value="{{ search_query }}">
    </label>
    <input type="submit" value="Search">
</form>

    {% for memorial in memorial %}

        <div class="post-container ">

             <h3 class="memorial-entry">
                 <a href="{% url 'Memorialdetail' memorial.pk %}">{{ memorial.firstname }},{{ memorial.lastname }}</a>
                        {% if memorial.image %}
                           <img src="{{memorial.image.url}}">
                       {%else %}
                            <p>No Image</p>
                        {% endif%}
             </h3>

        </div>

        {% empty %}
        <p>No posts available.</p>
        <p>No Memorials found matching your search</p>

    {% endfor %}

 </div>

{% endblock content %}

app/templates/app/Memorial/memorialupdate.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
      <h1> New Post</h1>
        <form action="{% url 'Memorialupdate' object.pk %}" method="post" enctype="multipart/form-data" class="formm">
            {% csrf_token %}
            {{form.as_p}}
            <input type = "submit" value="Update">


        </form>
{% endblock content %}